// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * w​t​f​-​c​s​s​-​u​n​i​t
	 */
	appName: string
	/**
	 * w​t​f​-​c​s​s​-​u​n​i​t​ ​-​ ​F​i​g​u​r​e​ ​o​u​t​ ​y​o​u​r​ ​C​S​S​ ​u​n​i​t​ ​w​i​t​h​ ​e​a​s​e​.​ ​A​l​l​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​d​o​ ​i​s​ ​j​u​s​t​ ​a​n​s​w​e​r​ ​s​o​m​e​ ​q​u​e​s​t​i​o​n​s​.
	 */
	title: string
	/**
	 * w​t​f​-​c​s​s​-​u​n​i​t​ ​i​s​ ​c​r​e​a​t​e​d​ ​b​y​ ​S​h​a​m​i​m​ ​H​o​s​s​a​i​n​ ​w​h​o​ ​i​s​ ​a​ ​f​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​ ​a​n​d​ ​a​ ​t​e​c​h​ ​e​n​t​h​u​s​i​a​s​t​ ​c​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​s​ ​f​r​o​n​t​e​n​d​ ​l​e​a​d​ ​@​s​e​c​u​r​e​s​h​i​p​ ​i​n​c​.​ ​H​e​ ​l​o​v​e​s​ ​t​o​ ​b​u​i​l​d​ ​p​r​o​d​u​c​t​s​ ​t​h​a​t​ ​h​e​l​p​ ​p​e​o​p​l​e​ ​t​o​ ​s​o​l​v​e​ ​t​h​e​i​r​ ​p​r​o​b​l​e​m​s​.​ ​S​o​m​e​t​i​m​e​s​ ​f​i​n​d​i​n​g​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​c​a​n​ ​b​e​ ​a​ ​p​a​i​n​.​ ​T​h​i​s​ ​t​o​o​l​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​t​o​ ​f​i​g​u​r​e​ ​o​u​t​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​j​e​c​t​.
	 */
	description: string
	/**
	 * C​S​S​ ​u​n​i​t​s​ ​t​o​o​l​,​ ​H​T​M​L​ ​S​E​O​ ​o​p​t​i​m​i​z​a​t​i​o​n​,​ ​w​e​b​ ​d​e​s​i​g​n​ ​C​S​S​ ​u​n​i​t​s​,​ ​C​S​S​ ​u​n​i​t​ ​c​o​n​v​e​r​t​e​r​,​ ​r​e​s​p​o​n​s​i​v​e​ ​d​e​s​i​g​n​ ​u​n​i​t​s​,​ ​p​i​x​e​l​ ​t​o​ ​e​m​ ​c​o​n​v​e​r​t​e​r​,​ ​C​S​S​ ​l​e​n​g​t​h​ ​u​n​i​t​s​,​ ​w​e​b​ ​d​e​v​e​l​o​p​m​e​n​t​ ​t​o​o​l​s​,​ ​C​S​S​ ​b​e​s​t​ ​p​r​a​c​t​i​c​e​s​,​ ​H​T​M​L​ ​c​o​d​i​n​g​ ​t​i​p​s​,​ ​w​e​b​ ​d​e​s​i​g​n​ ​o​p​t​i​m​i​z​a​t​i​o​n​,​ ​p​i​x​e​l​ ​c​o​n​v​e​r​s​i​o​n​ ​t​o​o​l​,​ ​E​M​ ​a​n​d​ ​R​E​M​ ​u​n​i​t​s​,​ ​C​S​S​ ​m​e​a​s​u​r​e​m​e​n​t​ ​g​u​i​d​e​,​ ​d​e​s​i​g​n​ ​u​n​i​t​ ​c​a​l​c​u​l​a​t​o​r​,​ ​r​e​s​p​o​n​s​i​v​e​ ​w​e​b​ ​u​n​i​t​s​,​ ​C​S​S​ ​l​a​y​o​u​t​ ​t​i​p​s​,​ ​w​e​b​ ​d​e​v​e​l​o​p​m​e​n​t​ ​r​e​s​o​u​r​c​e​s​,​ ​H​T​M​L​ ​c​o​d​i​n​g​ ​o​p​t​i​m​i​z​a​t​i​o​n​,​ ​p​i​x​e​l​-​p​e​r​f​e​c​t​ ​d​e​s​i​g​n​,​ ​w​t​f​-​c​s​s​-​u​n​i​t
	 */
	keywords: string
	/**
	 * @​s​h​a​m​s​c​o​r​n​e​r
	 */
	appTwitterAccount: string
	common: {
		/**
		 * e​t​c
		 */
		etc: string
		/**
		 * a​n​d​ ​m​a​n​y​ ​m​o​r​e​.​.​.
		 */
		andManyMore: string
		/**
		 * F​i​g​u​r​e​ ​o​u​t​ ​y​o​u​r​ ​C​S​S​ ​u​n​i​t​ ​w​i​t​h​ ​e​a​s​e​.​ ​A​l​l​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​d​o​ ​i​s​ ​j​u​s​t​ ​a​n​s​w​e​r​ ​s​o​m​e​ ​q​u​e​s​t​i​o​n​s​.
		 */
		slogan: string
		/**
		 * S​h​o​w
		 */
		show: string
		/**
		 * H​i​d​e
		 */
		hide: string
		/**
		 * Y​e​s
		 */
		yes: string
		/**
		 * N​o
		 */
		no: string
		/**
		 * R​e​s​e​t
		 */
		reset: string
		/**
		 * B​a​c​k
		 */
		back: string
	}
	appLogo: {
		/**
		 * w​t​f​-​c​s​s​-​u​n​i​t​ ​i​s​ ​c​r​e​a​t​e​d​ ​b​y​ ​S​h​a​m​i​m​ ​H​o​s​s​a​i​n​ ​w​h​o​ ​i​s​ ​a​ ​f​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​ ​a​n​d​ ​a​ ​t​e​c​h​ ​e​n​t​h​u​s​i​a​s​t​ ​c​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​s​ ​f​r​o​n​t​e​n​d​ ​l​e​a​d​ ​@​s​e​c​u​r​e​s​h​i​p​ ​i​n​c​.​ ​H​e​ ​l​o​v​e​s​ ​t​o​ ​b​u​i​l​d​ ​p​r​o​d​u​c​t​s​ ​t​h​a​t​ ​h​e​l​p​ ​p​e​o​p​l​e​ ​t​o​ ​s​o​l​v​e​ ​t​h​e​i​r​ ​p​r​o​b​l​e​m​s​.​ ​S​o​m​e​t​i​m​e​s​ ​f​i​n​d​i​n​g​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​c​a​n​ ​b​e​ ​a​ ​p​a​i​n​.​ ​T​h​i​s​ ​t​o​o​l​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​t​o​ ​f​i​g​u​r​e​ ​o​u​t​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​j​e​c​t​.
		 */
		hrefTitle: string
		/**
		 * w​t​f​-​c​s​s​-​u​n​i​t​ ​L​o​g​o
		 */
		alt: string
	}
	schemaMarkup: {
		/**
		 * C​o​r​p​o​r​a​t​i​o​n
		 */
		type: string
		/**
		 * s​h​a​m​s​c​o​r​n​e​r
		 */
		name: string
		/**
		 * w​t​f​-​c​s​s​-​u​n​i​t​ ​i​s​ ​c​r​e​a​t​e​d​ ​b​y​ ​S​h​a​m​i​m​ ​H​o​s​s​a​i​n​ ​w​h​o​ ​i​s​ ​a​ ​f​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​ ​a​n​d​ ​a​ ​t​e​c​h​ ​e​n​t​h​u​s​i​a​s​t​ ​c​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​s​ ​f​r​o​n​t​e​n​d​ ​l​e​a​d​ ​@​s​e​c​u​r​e​s​h​i​p​ ​i​n​c​.​ ​H​e​ ​l​o​v​e​s​ ​t​o​ ​b​u​i​l​d​ ​p​r​o​d​u​c​t​s​ ​t​h​a​t​ ​h​e​l​p​ ​p​e​o​p​l​e​ ​t​o​ ​s​o​l​v​e​ ​t​h​e​i​r​ ​p​r​o​b​l​e​m​s​.​ ​S​o​m​e​t​i​m​e​s​ ​f​i​n​d​i​n​g​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​c​a​n​ ​b​e​ ​a​ ​p​a​i​n​.​ ​T​h​i​s​ ​t​o​o​l​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​t​o​ ​f​i​g​u​r​e​ ​o​u​t​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​j​e​c​t​.
		 */
		markupDescription: string
		founder: {
			'0': {
				/**
				 * P​e​r​s​o​n
				 */
				type: string
				/**
				 * S​h​a​m​i​m​ ​H​o​s​s​a​i​n
				 */
				name: string
			}
		}
		/**
		 * 2​0​2​1​-​0​7​-​0​4
		 */
		foundingDate: string
		contactPoint: {
			'0': {
				/**
				 * C​o​n​t​a​c​t​P​o​i​n​t
				 */
				type: string
				/**
				 * h​o​s​s​a​i​n​s​1​5​9​@​g​m​a​i​l​.​c​o​m
				 */
				email: string
				telephone: string
				/**
				 * c​u​s​t​o​m​e​r​ ​s​e​r​v​i​c​e
				 */
				contactType: string
			}
		}
	}
	errorPage: {
		/**
		 * 4​0​4
		 */
		title: string
		/**
		 * N​o​t​ ​f​o​u​n​d
		 */
		subtitle: string
		/**
		 * 4​0​4
		 */
		pageTitle: string
		/**
		 * L​o​o​k​i​n​g​ ​f​o​r​ ​h​e​l​p​?​ ​R​e​a​c​h​ ​o​u​t​ ​t​o​ ​m​e​ ​a​t​ ​h​o​s​s​a​i​n​s​1​5​9​@​g​m​a​i​l​.​c​o​m
		 */
		description: string
		/**
		 * S​u​p​p​o​r​t​,​ ​C​o​n​t​a​c​t​,​ ​H​e​l​p​,​ ​4​0​4​,​ ​N​o​t​ ​f​o​u​n​d
		 */
		keywords: string
	}
	onboarding: {
		/**
		 * H​i​,​ ​I​'​m​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​f​o​n​t​-​s​e​m​i​b​o​l​d​"​>​S​h​a​m​i​m​ ​H​o​s​s​a​i​n​<​/​s​p​a​n​>
		 */
		greeting: string
		/**
		 * A​n​s​w​e​r​ ​s​o​m​e​ ​q​u​e​s​t​i​o​n​s​ ​a​n​d​ ​I​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​t​o​ ​f​i​g​u​r​e​ ​o​u​t​ ​t​h​e​ ​r​i​g​h​t​ ​C​S​S​ ​u​n​i​t​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​j​e​c​t​.
		 */
		title: string
		/**
		 * A​s​s​u​m​i​n​g​ ​y​o​u​ ​a​r​e​ ​o​n​l​y​ ​u​s​i​n​g​ ​t​h​e​s​e​ ​u​n​i​t​s​ ​f​o​r​ ​w​e​b​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​n​o​t​ ​f​o​r​ ​p​r​i​n​t​ ​m​e​d​i​a​.
		 */
		subtitle: string
		callToAction: {
			/**
			 * L​e​t​'​s​ ​S​t​a​r​t
			 */
			letsStart: string
		}
	}
	questionaries: {
		whatDeclaring: {
			/**
			 * W​h​a​t​ ​a​r​e​ ​y​o​u​ ​d​e​c​l​a​r​i​n​g​?
			 */
			title: string
			items: {
				'0': {
					/**
					 * F​o​n​t​ ​s​i​z​e
					 */
					title: string
					/**
					 * f​o​n​t​-​s​i​z​e
					 */
					value: string
					hint: string
				}
				'1': {
					/**
					 * S​p​a​c​i​n​g
					 */
					title: string
					/**
					 * s​p​a​c​i​n​g
					 */
					value: string
					/**
					 * M​a​r​g​i​n​,​ ​p​a​d​d​i​n​g​,​ ​g​a​p​,​ ​e​t​c​.
					 */
					hint: string
				}
				'2': {
					/**
					 * P​o​s​i​t​i​o​n​i​n​g
					 */
					title: string
					/**
					 * p​o​s​i​t​i​o​n​i​n​g
					 */
					value: string
					/**
					 * T​o​p​,​ ​r​i​g​h​t​,​ ​b​o​t​t​o​m​,​ ​l​e​f​t​,​ ​e​t​c​.
					 */
					hint: string
				}
				'3': {
					/**
					 * D​e​t​a​i​l​s​/​e​f​f​e​c​t​s
					 */
					title: string
					/**
					 * d​e​t​a​i​l​s​-​e​f​f​e​c​t​s
					 */
					value: string
					/**
					 * B​o​r​d​e​r​,​ ​b​o​x​-​s​h​a​d​o​w​,​ ​o​u​t​l​i​n​e​s​,​ ​e​t​c​.
					 */
					hint: string
				}
				'4': {
					/**
					 * F​l​e​x​ ​o​r​ ​g​r​i​d
					 */
					title: string
					/**
					 * f​l​e​x​-​g​r​i​d
					 */
					value: string
					hint: string
				}
				'5': {
					/**
					 * W​i​d​t​h​ ​o​r​ ​h​e​i​g​h​t​ ​o​n​ ​a​n​ ​e​l​e​m​e​n​t
					 */
					title: string
					/**
					 * w​i​d​t​h​-​h​e​i​g​h​t
					 */
					value: string
					hint: string
				}
			}
		}
		fontSize: {
			/**
			 * W​h​i​c​h​ ​o​f​ ​t​h​e​s​e​ ​a​r​e​ ​y​o​u​ ​s​e​l​e​c​t​i​n​g​ ​t​o​ ​d​e​c​l​a​r​e​ ​t​h​e​ ​f​o​n​t​-​s​i​z​e​?
			 */
			title: string
			items: {
				'0': {
					/**
					 * T​h​e​ ​<​h​t​m​l​>​ ​e​l​e​m​e​n​t
					 */
					title: string
					/**
					 * h​t​m​l
					 */
					value: string
					hint: string
				}
				'1': {
					/**
					 * T​h​e​ ​<​b​o​d​y​>​ ​e​l​e​m​e​n​t
					 */
					title: string
					/**
					 * b​o​d​y
					 */
					value: string
					hint: string
				}
				'2': {
					/**
					 * T​e​x​t​ ​r​e​l​a​t​e​d​ ​e​l​e​m​e​n​t
					 */
					title: string
					/**
					 * t​e​x​t​-​r​e​l​a​t​e​d
					 */
					value: string
					/**
					 * <​h​1​>​ ​-​ ​<​h​6​>​,​ ​<​p​>​,​ ​<​o​l​>​,​ ​<​u​l​>​,​ ​e​t​c​.
					 */
					hint: string
				}
				'3': {
					/**
					 * I​n​l​i​n​e​ ​e​l​e​m​e​n​t
					 */
					title: string
					/**
					 * i​n​l​i​n​e
					 */
					value: string
					/**
					 * <​a​>​,​ ​<​s​p​a​n​>​,​ ​<​s​t​r​o​n​g​>​,​ ​e​t​c​.
					 */
					hint: string
				}
				'4': {
					/**
					 * L​a​y​o​u​t​ ​e​l​e​m​e​n​t
					 */
					title: string
					/**
					 * l​a​y​o​u​t
					 */
					value: string
					/**
					 * <​d​i​v​>​,​ ​<​n​a​v​>​,​ ​<​m​a​i​n​>​,​ ​<​a​s​i​d​e​>​,​ ​<​f​o​o​t​e​r​>​,​ ​e​t​c​.
					 */
					hint: string
				}
			}
			setHere: {
				/**
				 * D​o​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​s​e​t​ ​a​ ​f​o​n​t​-​s​i​z​e​ ​h​e​r​e​?
				 */
				title: string
				items: {
					'0': {
						/**
						 * Y​e​s​!
						 */
						title: string
						/**
						 * y​e​s
						 */
						value: string
						hint: string
					}
					'1': {
						/**
						 * N​o​,​ ​I​ ​g​u​e​s​s​ ​n​o​t​.
						 */
						title: string
						/**
						 * n​o
						 */
						value: string
						hint: string
					}
				}
				/**
				 * Y​o​u​ ​p​r​o​b​a​b​l​y​ ​d​o​n​'​t​ ​n​e​e​d​ ​t​o​ ​b​o​t​h​e​r​ ​(​a​n​d​ ​t​h​e​ ​6​2​.​5​%​ ​t​e​n​d​s​ ​t​o​ ​b​e​ ​s​o​m​e​t​h​i​n​g​ ​y​o​u​ ​s​h​o​u​l​d​ ​a​v​o​i​d​.​)
				 */
				noFinal: string
			}
		}
		whichFontSize: {
			/**
			 * W​h​i​c​h​ ​o​f​ ​t​h​e​s​e​ ​a​r​e​ ​y​o​u​ ​s​e​l​e​c​t​i​n​g​ ​t​o​ ​d​e​c​l​a​r​e​ ​t​h​e​ ​f​o​n​t​-​s​i​z​e​?
			 */
			title: string
			question: {
				items: {
					'0': {
						/**
						 * T​h​e​ ​<​h​t​m​l​>​ ​e​l​e​m​e​n​t
						 */
						title: string
						/**
						 * h​t​m​l
						 */
						value: string
						hint: string
						question: {
							/**
							 * D​o​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​s​e​t​ ​a​ ​f​o​n​t​-​s​i​z​e​ ​h​e​r​e​?
							 */
							title: string
							items: {
								'0': {
									/**
									 * N​o​,​ ​I​ ​g​u​e​s​s​ ​n​o​t​.
									 */
									title: string
									/**
									 * n​o
									 */
									value: string
									hint: string
									answer: {
										'0': {
											title: string
											/**
											 * Y​o​u​ ​p​r​o​b​a​b​l​y​ ​d​o​n​'​t​ ​n​e​e​d​ ​t​o​ ​b​o​t​h​e​r​ ​(​a​n​d​ ​t​h​e​ ​6​2​.​5​%​ ​t​e​n​d​s​ ​t​o​ ​b​e​ ​s​o​m​e​t​h​i​n​g​ ​y​o​u​ ​s​h​o​u​l​d​ ​a​v​o​i​d​.​)
											 */
											description: string
										}
									}
								}
								'1': {
									/**
									 * Y​e​s​!
									 */
									title: string
									/**
									 * y​e​s
									 */
									value: string
									hint: string
									question: {
										/**
										 * D​o​ ​y​o​u​ ​w​a​n​t​ ​i​t​ ​t​o​ ​b​e​ ​r​e​s​p​o​n​s​i​v​e​?
										 */
										title: string
										items: {
											'0': {
												/**
												 * N​o​!
												 */
												title: string
												/**
												 * n​o
												 */
												value: string
												hint: string
												answer: {
													'0': {
														/**
														 * r​e​m
														 */
														title: string
														/**
														 * M​o​s​t​ ​o​f​ ​t​h​e​ ​t​i​m​e​,​ ​y​o​u​ ​w​i​l​l​ ​p​r​o​b​a​b​l​y​ ​u​s​e​ ​r​e​m​ ​w​h​e​n​ ​d​e​c​l​a​r​i​n​g​ ​f​o​n​t​ ​s​i​z​e​s​.​ ​I​t​'​s​ ​e​a​s​y​ ​t​o​ ​u​s​e​,​ ​p​r​e​d​i​c​t​a​b​l​e​,​ ​a​n​d​ ​v​e​r​y​ ​i​m​p​o​r​t​a​n​t​l​y​,​ ​r​e​s​p​e​c​t​s​ ​t​h​e​ ​u​s​e​r​s​ ​c​h​o​i​c​e​ ​i​f​ ​t​h​e​y​ ​h​a​v​e​ ​m​a​d​e​ ​c​h​a​n​g​e​s​ ​t​o​ ​t​h​e​i​r​ ​d​e​f​a​u​l​t​ ​f​o​n​t​ ​s​i​z​e​ ​a​t​ ​t​h​e​ ​O​S​ ​o​r​ ​b​r​o​w​s​e​r​ ​l​e​v​e​l​.
														 */
														description: string
													}
												}
											}
											'1': {
												/**
												 * Y​e​s​!
												 */
												title: string
												/**
												 * y​e​s
												 */
												value: string
												hint: string
												answer: {
													'0': {
														/**
														 * C​l​a​m​p​(​)
														 */
														title: string
														/**
														 * Y​o​u​ ​n​e​e​d​ ​3​ ​v​a​l​u​e​s​ ​f​o​r​ ​c​l​a​m​p​,​ ​a​ ​m​i​n​i​m​u​m​,​ ​"​g​r​o​w​t​h​ ​f​a​c​t​o​r​"​,​ ​a​n​d​ ​m​a​x​i​m​u​m​.​ ​T​h​e​ ​m​i​n​i​m​u​m​ ​a​n​d​ ​m​a​x​i​m​u​m​ ​s​h​o​u​l​d​ ​p​r​o​b​a​b​l​y​ ​b​e​ ​i​n​ ​r​e​m​ ​a​n​d​ ​t​h​e​ ​g​r​o​w​t​h​ ​f​a​c​t​o​r​ ​a​ ​v​i​e​w​p​o​r​t​ ​u​n​i​t​,​ ​b​u​t​ ​a​l​s​o​ ​w​i​t​h​ ​r​e​m​ ​a​d​d​e​d​ ​t​o​ ​i​t​.​ ​F​o​r​ ​e​x​a​m​p​l​e​:​ ​c​l​a​m​p​(​1​.​2​5​r​e​m​,​ ​7​.​5​v​w​ ​+​ ​.​5​r​e​m​,​ ​2​r​e​m​)​.​<​b​r​>​<​b​r​>​Y​o​u​ ​c​a​n​ ​l​e​a​r​n​ ​m​o​r​e​ ​a​b​o​u​t​ ​i​t​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​w​w​w​.​y​o​u​t​u​b​e​.​c​o​m​/​w​a​t​c​h​?​v​=​U​9​V​F​-​4​e​u​y​R​o​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​ ​n​o​r​e​f​e​r​r​e​r​"​>​i​n​ ​t​h​i​s​ ​v​i​d​e​o​<​/​a​>​.​ ​T​h​e​r​e​ ​i​s​ ​a​l​s​o​ ​a​ ​f​a​n​t​a​s​t​i​c​ ​t​o​o​l​ ​c​a​l​l​e​d​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​u​t​o​p​i​a​.​f​y​i​/​t​y​p​e​/​c​a​l​c​u​l​a​t​o​r​/​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​ ​n​o​r​e​f​e​r​r​e​r​"​>​U​t​o​p​i​a​<​/​a​>​ ​t​h​a​t​ ​y​o​u​ ​c​a​n​ ​u​s​e​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​a​ ​r​e​s​p​o​n​s​i​v​e​ ​t​y​p​e​ ​s​c​a​l​e​.
														 */
														description: string
													}
													'1': {
														/**
														 * c​q​i
														 */
														title: string
														/**
														 * I​f​ ​y​o​u​ ​d​o​n​'​t​ ​m​i​n​d​ ​t​r​y​i​n​g​ ​s​o​m​e​t​h​i​n​g​ ​t​h​a​t​ ​d​o​e​s​n​'​t​ ​h​a​v​e​ ​t​h​e​ ​b​e​s​t​ ​b​r​o​w​s​e​r​ ​s​u​p​p​o​r​t​,​ ​y​o​u​ ​c​o​u​l​d​ ​s​u​b​s​t​i​t​u​t​e​ ​t​h​e​ ​`​v​w​`​ ​u​n​i​t​ ​w​i​t​h​ ​a​ ​`​c​q​i​`​,​ ​w​h​i​c​h​ ​i​s​ ​a​ ​c​o​n​t​a​i​n​e​r​ ​q​u​e​r​y​ ​u​n​i​t​ ​t​h​a​t​ ​g​e​t​s​ ​t​h​e​ ​i​n​l​i​n​e​ ​s​i​z​e​ ​o​f​ ​i​t​'​s​ ​c​o​n​t​a​i​n​e​r​.​ ​T​h​i​s​ ​d​o​e​s​ ​m​e​a​n​ ​y​o​u​ ​n​e​e​d​ ​a​ ​c​o​n​t​a​i​n​e​r​ ​t​h​o​u​g​h​.​ ​Y​o​u​ ​c​a​n​ ​l​e​a​r​n​ ​m​o​r​e​ ​a​b​o​u​t​ ​i​t​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​w​w​w​.​y​o​u​t​u​b​e​.​c​o​m​/​w​a​t​c​h​?​v​=​Z​S​a​A​H​b​5​d​R​w​Q​"​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​r​e​l​=​"​n​o​o​p​e​n​e​r​ ​n​o​r​e​f​e​r​r​e​r​"​>​i​n​ ​t​h​i​s​ ​v​i​d​e​o​<​/​a​>​.
														 */
														description: string
													}
												}
											}
										}
									}
								}
							}
						}
						answers: {
						}
					}
				}
			}
		}
	}
	errors: {
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
		 */
		somethingWentWrong: string
	}
}

export type TranslationFunctions = {
	/**
	 * wtf-css-unit
	 */
	appName: () => LocalizedString
	/**
	 * wtf-css-unit - Figure out your CSS unit with ease. All you need to do is just answer some questions.
	 */
	title: () => LocalizedString
	/**
	 * wtf-css-unit is created by Shamim Hossain who is a full-stack developer and a tech enthusiast currently working as frontend lead @secureship inc. He loves to build products that help people to solve their problems. Sometimes finding the right css units can be a pain. This tool will help you to figure out the right css units for your project.
	 */
	description: () => LocalizedString
	/**
	 * CSS units tool, HTML SEO optimization, web design CSS units, CSS unit converter, responsive design units, pixel to em converter, CSS length units, web development tools, CSS best practices, HTML coding tips, web design optimization, pixel conversion tool, EM and REM units, CSS measurement guide, design unit calculator, responsive web units, CSS layout tips, web development resources, HTML coding optimization, pixel-perfect design, wtf-css-unit
	 */
	keywords: () => LocalizedString
	/**
	 * @shamscorner
	 */
	appTwitterAccount: () => LocalizedString
	common: {
		/**
		 * etc
		 */
		etc: () => LocalizedString
		/**
		 * and many more...
		 */
		andManyMore: () => LocalizedString
		/**
		 * Figure out your CSS unit with ease. All you need to do is just answer some questions.
		 */
		slogan: () => LocalizedString
		/**
		 * Show
		 */
		show: () => LocalizedString
		/**
		 * Hide
		 */
		hide: () => LocalizedString
		/**
		 * Yes
		 */
		yes: () => LocalizedString
		/**
		 * No
		 */
		no: () => LocalizedString
		/**
		 * Reset
		 */
		reset: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
	}
	appLogo: {
		/**
		 * wtf-css-unit is created by Shamim Hossain who is a full-stack developer and a tech enthusiast currently working as frontend lead @secureship inc. He loves to build products that help people to solve their problems. Sometimes finding the right css units can be a pain. This tool will help you to figure out the right css units for your project.
		 */
		hrefTitle: () => LocalizedString
		/**
		 * wtf-css-unit Logo
		 */
		alt: () => LocalizedString
	}
	schemaMarkup: {
		/**
		 * Corporation
		 */
		type: () => LocalizedString
		/**
		 * shamscorner
		 */
		name: () => LocalizedString
		/**
		 * wtf-css-unit is created by Shamim Hossain who is a full-stack developer and a tech enthusiast currently working as frontend lead @secureship inc. He loves to build products that help people to solve their problems. Sometimes finding the right css units can be a pain. This tool will help you to figure out the right css units for your project.
		 */
		markupDescription: () => LocalizedString
		founder: {
			'0': {
				/**
				 * Person
				 */
				type: () => LocalizedString
				/**
				 * Shamim Hossain
				 */
				name: () => LocalizedString
			}
		}
		/**
		 * 2021-07-04
		 */
		foundingDate: () => LocalizedString
		contactPoint: {
			'0': {
				/**
				 * ContactPoint
				 */
				type: () => LocalizedString
				/**
				 * hossains159@gmail.com
				 */
				email: () => LocalizedString
				telephone: () => LocalizedString
				/**
				 * customer service
				 */
				contactType: () => LocalizedString
			}
		}
	}
	errorPage: {
		/**
		 * 404
		 */
		title: () => LocalizedString
		/**
		 * Not found
		 */
		subtitle: () => LocalizedString
		/**
		 * 404
		 */
		pageTitle: () => LocalizedString
		/**
		 * Looking for help? Reach out to me at hossains159@gmail.com
		 */
		description: () => LocalizedString
		/**
		 * Support, Contact, Help, 404, Not found
		 */
		keywords: () => LocalizedString
	}
	onboarding: {
		/**
		 * Hi, I'm <span class="font-semibold">Shamim Hossain</span>
		 */
		greeting: () => LocalizedString
		/**
		 * Answer some questions and I will help you to figure out the right CSS unit for your project.
		 */
		title: () => LocalizedString
		/**
		 * Assuming you are only using these units for web development, not for print media.
		 */
		subtitle: () => LocalizedString
		callToAction: {
			/**
			 * Let's Start
			 */
			letsStart: () => LocalizedString
		}
	}
	questionaries: {
		whatDeclaring: {
			/**
			 * What are you declaring?
			 */
			title: () => LocalizedString
			items: {
				'0': {
					/**
					 * Font size
					 */
					title: () => LocalizedString
					/**
					 * font-size
					 */
					value: () => LocalizedString
					hint: () => LocalizedString
				}
				'1': {
					/**
					 * Spacing
					 */
					title: () => LocalizedString
					/**
					 * spacing
					 */
					value: () => LocalizedString
					/**
					 * Margin, padding, gap, etc.
					 */
					hint: () => LocalizedString
				}
				'2': {
					/**
					 * Positioning
					 */
					title: () => LocalizedString
					/**
					 * positioning
					 */
					value: () => LocalizedString
					/**
					 * Top, right, bottom, left, etc.
					 */
					hint: () => LocalizedString
				}
				'3': {
					/**
					 * Details/effects
					 */
					title: () => LocalizedString
					/**
					 * details-effects
					 */
					value: () => LocalizedString
					/**
					 * Border, box-shadow, outlines, etc.
					 */
					hint: () => LocalizedString
				}
				'4': {
					/**
					 * Flex or grid
					 */
					title: () => LocalizedString
					/**
					 * flex-grid
					 */
					value: () => LocalizedString
					hint: () => LocalizedString
				}
				'5': {
					/**
					 * Width or height on an element
					 */
					title: () => LocalizedString
					/**
					 * width-height
					 */
					value: () => LocalizedString
					hint: () => LocalizedString
				}
			}
		}
		fontSize: {
			/**
			 * Which of these are you selecting to declare the font-size?
			 */
			title: () => LocalizedString
			items: {
				'0': {
					/**
					 * The <html> element
					 */
					title: () => LocalizedString
					/**
					 * html
					 */
					value: () => LocalizedString
					hint: () => LocalizedString
				}
				'1': {
					/**
					 * The <body> element
					 */
					title: () => LocalizedString
					/**
					 * body
					 */
					value: () => LocalizedString
					hint: () => LocalizedString
				}
				'2': {
					/**
					 * Text related element
					 */
					title: () => LocalizedString
					/**
					 * text-related
					 */
					value: () => LocalizedString
					/**
					 * <h1> - <h6>, <p>, <ol>, <ul>, etc.
					 */
					hint: () => LocalizedString
				}
				'3': {
					/**
					 * Inline element
					 */
					title: () => LocalizedString
					/**
					 * inline
					 */
					value: () => LocalizedString
					/**
					 * <a>, <span>, <strong>, etc.
					 */
					hint: () => LocalizedString
				}
				'4': {
					/**
					 * Layout element
					 */
					title: () => LocalizedString
					/**
					 * layout
					 */
					value: () => LocalizedString
					/**
					 * <div>, <nav>, <main>, <aside>, <footer>, etc.
					 */
					hint: () => LocalizedString
				}
			}
			setHere: {
				/**
				 * Do you need to set a font-size here?
				 */
				title: () => LocalizedString
				items: {
					'0': {
						/**
						 * Yes!
						 */
						title: () => LocalizedString
						/**
						 * yes
						 */
						value: () => LocalizedString
						hint: () => LocalizedString
					}
					'1': {
						/**
						 * No, I guess not.
						 */
						title: () => LocalizedString
						/**
						 * no
						 */
						value: () => LocalizedString
						hint: () => LocalizedString
					}
				}
				/**
				 * You probably don't need to bother (and the 62.5% tends to be something you should avoid.)
				 */
				noFinal: () => LocalizedString
			}
		}
		whichFontSize: {
			/**
			 * Which of these are you selecting to declare the font-size?
			 */
			title: () => LocalizedString
			question: {
				items: {
					'0': {
						/**
						 * The <html> element
						 */
						title: () => LocalizedString
						/**
						 * html
						 */
						value: () => LocalizedString
						hint: () => LocalizedString
						question: {
							/**
							 * Do you need to set a font-size here?
							 */
							title: () => LocalizedString
							items: {
								'0': {
									/**
									 * No, I guess not.
									 */
									title: () => LocalizedString
									/**
									 * no
									 */
									value: () => LocalizedString
									hint: () => LocalizedString
									answer: {
										'0': {
											title: () => LocalizedString
											/**
											 * You probably don't need to bother (and the 62.5% tends to be something you should avoid.)
											 */
											description: () => LocalizedString
										}
									}
								}
								'1': {
									/**
									 * Yes!
									 */
									title: () => LocalizedString
									/**
									 * yes
									 */
									value: () => LocalizedString
									hint: () => LocalizedString
									question: {
										/**
										 * Do you want it to be responsive?
										 */
										title: () => LocalizedString
										items: {
											'0': {
												/**
												 * No!
												 */
												title: () => LocalizedString
												/**
												 * no
												 */
												value: () => LocalizedString
												hint: () => LocalizedString
												answer: {
													'0': {
														/**
														 * rem
														 */
														title: () => LocalizedString
														/**
														 * Most of the time, you will probably use rem when declaring font sizes. It's easy to use, predictable, and very importantly, respects the users choice if they have made changes to their default font size at the OS or browser level.
														 */
														description: () => LocalizedString
													}
												}
											}
											'1': {
												/**
												 * Yes!
												 */
												title: () => LocalizedString
												/**
												 * yes
												 */
												value: () => LocalizedString
												hint: () => LocalizedString
												answer: {
													'0': {
														/**
														 * Clamp()
														 */
														title: () => LocalizedString
														/**
														 * You need 3 values for clamp, a minimum, "growth factor", and maximum. The minimum and maximum should probably be in rem and the growth factor a viewport unit, but also with rem added to it. For example: clamp(1.25rem, 7.5vw + .5rem, 2rem).<br><br>You can learn more about it <a href="https://www.youtube.com/watch?v=U9VF-4euyRo" target="_blank" rel="noopener noreferrer">in this video</a>. There is also a fantastic tool called <a href="https://utopia.fyi/type/calculator/" target="_blank" rel="noopener noreferrer">Utopia</a> that you can use to generate a responsive type scale.
														 */
														description: () => LocalizedString
													}
													'1': {
														/**
														 * cqi
														 */
														title: () => LocalizedString
														/**
														 * If you don't mind trying something that doesn't have the best browser support, you could substitute the `vw` unit with a `cqi`, which is a container query unit that gets the inline size of it's container. This does mean you need a container though. You can learn more about it <a href="https://www.youtube.com/watch?v=ZSaAHb5dRwQ" target="_blank" rel="noopener noreferrer">in this video</a>.
														 */
														description: () => LocalizedString
													}
												}
											}
										}
									}
								}
							}
						}
						answers: {
						}
					}
				}
			}
		}
	}
	errors: {
		/**
		 * Something went wrong
		 */
		somethingWentWrong: () => LocalizedString
	}
}

export type Formatters = {}
