// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * w​t​f​-​c​s​s​-​u​n​i​t
	 */
	appName: string
	/**
	 * w​t​f​-​c​s​s​-​u​n​i​t​ ​-​ ​F​i​g​u​r​e​ ​o​u​t​ ​y​o​u​r​ ​C​S​S​ ​u​n​i​t​ ​w​i​t​h​ ​e​a​s​e​.​ ​A​l​l​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​d​o​ ​i​s​ ​j​u​s​t​ ​a​n​s​w​e​r​ ​s​o​m​e​ ​q​u​e​s​t​i​o​n​s​.
	 */
	title: string
	/**
	 * w​t​f​-​c​s​s​-​u​n​i​t​ ​i​s​ ​c​r​e​a​t​e​d​ ​b​y​ ​S​h​a​m​i​m​ ​H​o​s​s​a​i​n​ ​w​h​o​ ​i​s​ ​a​ ​f​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​ ​a​n​d​ ​a​ ​t​e​c​h​ ​e​n​t​h​u​s​i​a​s​t​ ​c​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​s​ ​f​r​o​n​t​e​n​d​ ​l​e​a​d​ ​@​s​e​c​u​r​e​s​h​i​p​ ​i​n​c​.​ ​H​e​ ​l​o​v​e​s​ ​t​o​ ​b​u​i​l​d​ ​p​r​o​d​u​c​t​s​ ​t​h​a​t​ ​h​e​l​p​ ​p​e​o​p​l​e​ ​t​o​ ​s​o​l​v​e​ ​t​h​e​i​r​ ​p​r​o​b​l​e​m​s​.​ ​S​o​m​e​t​i​m​e​s​ ​f​i​n​d​i​n​g​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​c​a​n​ ​b​e​ ​a​ ​p​a​i​n​.​ ​T​h​i​s​ ​t​o​o​l​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​t​o​ ​f​i​g​u​r​e​ ​o​u​t​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​j​e​c​t​.
	 */
	description: string
	/**
	 * C​S​S​ ​u​n​i​t​s​ ​t​o​o​l​,​ ​H​T​M​L​ ​S​E​O​ ​o​p​t​i​m​i​z​a​t​i​o​n​,​ ​w​e​b​ ​d​e​s​i​g​n​ ​C​S​S​ ​u​n​i​t​s​,​ ​C​S​S​ ​u​n​i​t​ ​c​o​n​v​e​r​t​e​r​,​ ​r​e​s​p​o​n​s​i​v​e​ ​d​e​s​i​g​n​ ​u​n​i​t​s​,​ ​p​i​x​e​l​ ​t​o​ ​e​m​ ​c​o​n​v​e​r​t​e​r​,​ ​C​S​S​ ​l​e​n​g​t​h​ ​u​n​i​t​s​,​ ​w​e​b​ ​d​e​v​e​l​o​p​m​e​n​t​ ​t​o​o​l​s​,​ ​C​S​S​ ​b​e​s​t​ ​p​r​a​c​t​i​c​e​s​,​ ​H​T​M​L​ ​c​o​d​i​n​g​ ​t​i​p​s​,​ ​w​e​b​ ​d​e​s​i​g​n​ ​o​p​t​i​m​i​z​a​t​i​o​n​,​ ​p​i​x​e​l​ ​c​o​n​v​e​r​s​i​o​n​ ​t​o​o​l​,​ ​E​M​ ​a​n​d​ ​R​E​M​ ​u​n​i​t​s​,​ ​C​S​S​ ​m​e​a​s​u​r​e​m​e​n​t​ ​g​u​i​d​e​,​ ​d​e​s​i​g​n​ ​u​n​i​t​ ​c​a​l​c​u​l​a​t​o​r​,​ ​r​e​s​p​o​n​s​i​v​e​ ​w​e​b​ ​u​n​i​t​s​,​ ​C​S​S​ ​l​a​y​o​u​t​ ​t​i​p​s​,​ ​w​e​b​ ​d​e​v​e​l​o​p​m​e​n​t​ ​r​e​s​o​u​r​c​e​s​,​ ​H​T​M​L​ ​c​o​d​i​n​g​ ​o​p​t​i​m​i​z​a​t​i​o​n​,​ ​p​i​x​e​l​-​p​e​r​f​e​c​t​ ​d​e​s​i​g​n​,​ ​w​t​f​-​c​s​s​-​u​n​i​t
	 */
	keywords: string
	/**
	 * @​s​h​a​m​s​c​o​r​n​e​r
	 */
	appTwitterAccount: string
	common: {
		/**
		 * e​t​c
		 */
		etc: string
		/**
		 * a​n​d​ ​m​a​n​y​ ​m​o​r​e​.​.​.
		 */
		andManyMore: string
		/**
		 * F​i​g​u​r​e​ ​o​u​t​ ​y​o​u​r​ ​C​S​S​ ​u​n​i​t​ ​w​i​t​h​ ​e​a​s​e​.​ ​A​l​l​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​d​o​ ​i​s​ ​j​u​s​t​ ​a​n​s​w​e​r​ ​s​o​m​e​ ​q​u​e​s​t​i​o​n​s​.
		 */
		slogan: string
		/**
		 * S​h​o​w
		 */
		show: string
		/**
		 * H​i​d​e
		 */
		hide: string
	}
	appLogo: {
		/**
		 * w​t​f​-​c​s​s​-​u​n​i​t​ ​i​s​ ​c​r​e​a​t​e​d​ ​b​y​ ​S​h​a​m​i​m​ ​H​o​s​s​a​i​n​ ​w​h​o​ ​i​s​ ​a​ ​f​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​ ​a​n​d​ ​a​ ​t​e​c​h​ ​e​n​t​h​u​s​i​a​s​t​ ​c​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​s​ ​f​r​o​n​t​e​n​d​ ​l​e​a​d​ ​@​s​e​c​u​r​e​s​h​i​p​ ​i​n​c​.​ ​H​e​ ​l​o​v​e​s​ ​t​o​ ​b​u​i​l​d​ ​p​r​o​d​u​c​t​s​ ​t​h​a​t​ ​h​e​l​p​ ​p​e​o​p​l​e​ ​t​o​ ​s​o​l​v​e​ ​t​h​e​i​r​ ​p​r​o​b​l​e​m​s​.​ ​S​o​m​e​t​i​m​e​s​ ​f​i​n​d​i​n​g​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​c​a​n​ ​b​e​ ​a​ ​p​a​i​n​.​ ​T​h​i​s​ ​t​o​o​l​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​t​o​ ​f​i​g​u​r​e​ ​o​u​t​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​j​e​c​t​.
		 */
		hrefTitle: string
		/**
		 * w​t​f​-​c​s​s​-​u​n​i​t​ ​L​o​g​o
		 */
		alt: string
	}
	schemaMarkup: {
		/**
		 * C​o​r​p​o​r​a​t​i​o​n
		 */
		type: string
		/**
		 * s​h​a​m​s​c​o​r​n​e​r
		 */
		name: string
		/**
		 * w​t​f​-​c​s​s​-​u​n​i​t​ ​i​s​ ​c​r​e​a​t​e​d​ ​b​y​ ​S​h​a​m​i​m​ ​H​o​s​s​a​i​n​ ​w​h​o​ ​i​s​ ​a​ ​f​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​e​r​ ​a​n​d​ ​a​ ​t​e​c​h​ ​e​n​t​h​u​s​i​a​s​t​ ​c​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​a​s​ ​f​r​o​n​t​e​n​d​ ​l​e​a​d​ ​@​s​e​c​u​r​e​s​h​i​p​ ​i​n​c​.​ ​H​e​ ​l​o​v​e​s​ ​t​o​ ​b​u​i​l​d​ ​p​r​o​d​u​c​t​s​ ​t​h​a​t​ ​h​e​l​p​ ​p​e​o​p​l​e​ ​t​o​ ​s​o​l​v​e​ ​t​h​e​i​r​ ​p​r​o​b​l​e​m​s​.​ ​S​o​m​e​t​i​m​e​s​ ​f​i​n​d​i​n​g​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​c​a​n​ ​b​e​ ​a​ ​p​a​i​n​.​ ​T​h​i​s​ ​t​o​o​l​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​t​o​ ​f​i​g​u​r​e​ ​o​u​t​ ​t​h​e​ ​r​i​g​h​t​ ​c​s​s​ ​u​n​i​t​s​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​j​e​c​t​.
		 */
		markupDescription: string
		founder: {
			'0': {
				/**
				 * P​e​r​s​o​n
				 */
				type: string
				/**
				 * S​h​a​m​i​m​ ​H​o​s​s​a​i​n
				 */
				name: string
			}
		}
		/**
		 * 2​0​2​1​-​0​7​-​0​4
		 */
		foundingDate: string
		contactPoint: {
			'0': {
				/**
				 * C​o​n​t​a​c​t​P​o​i​n​t
				 */
				type: string
				/**
				 * h​o​s​s​a​i​n​s​1​5​9​@​g​m​a​i​l​.​c​o​m
				 */
				email: string
				telephone: string
				/**
				 * c​u​s​t​o​m​e​r​ ​s​e​r​v​i​c​e
				 */
				contactType: string
			}
		}
	}
	errorPage: {
		/**
		 * 4​0​4
		 */
		title: string
		/**
		 * N​o​t​ ​f​o​u​n​d
		 */
		subtitle: string
		/**
		 * 4​0​4
		 */
		pageTitle: string
		/**
		 * L​o​o​k​i​n​g​ ​f​o​r​ ​h​e​l​p​?​ ​R​e​a​c​h​ ​o​u​t​ ​t​o​ ​m​e​ ​a​t​ ​h​o​s​s​a​i​n​s​1​5​9​@​g​m​a​i​l​.​c​o​m
		 */
		description: string
		/**
		 * S​u​p​p​o​r​t​,​ ​C​o​n​t​a​c​t​,​ ​H​e​l​p​,​ ​4​0​4​,​ ​N​o​t​ ​f​o​u​n​d
		 */
		keywords: string
	}
	onboarding: {
		/**
		 * H​i​,​ ​I​'​m​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​f​o​n​t​-​s​e​m​i​b​o​l​d​"​>​S​h​a​m​i​m​ ​H​o​s​s​a​i​n​<​/​s​p​a​n​>
		 */
		greeting: string
		/**
		 * A​n​s​w​e​r​ ​s​o​m​e​ ​q​u​e​s​t​i​o​n​s​ ​a​n​d​ ​I​ ​w​i​l​l​ ​h​e​l​p​ ​y​o​u​ ​t​o​ ​f​i​g​u​r​e​ ​o​u​t​ ​t​h​e​ ​r​i​g​h​t​ ​C​S​S​ ​u​n​i​t​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​j​e​c​t​.
		 */
		title: string
		/**
		 * A​s​s​u​m​i​n​g​ ​y​o​u​ ​a​r​e​ ​o​n​l​y​ ​u​s​i​n​g​ ​t​h​e​s​e​ ​u​n​i​t​s​ ​f​o​r​ ​w​e​b​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​n​o​t​ ​f​o​r​ ​p​r​i​n​t​ ​m​e​d​i​a​.
		 */
		subtitle: string
		callToAction: {
			/**
			 * L​e​t​'​s​ ​S​t​a​r​t
			 */
			letsStart: string
		}
	}
	questionaries: {
		/**
		 * W​h​a​t​ ​a​r​e​ ​y​o​u​ ​d​e​c​l​a​r​i​n​g​?
		 */
		title: string
	}
	errors: {
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
		 */
		somethingWentWrong: string
	}
}

export type TranslationFunctions = {
	/**
	 * wtf-css-unit
	 */
	appName: () => LocalizedString
	/**
	 * wtf-css-unit - Figure out your CSS unit with ease. All you need to do is just answer some questions.
	 */
	title: () => LocalizedString
	/**
	 * wtf-css-unit is created by Shamim Hossain who is a full-stack developer and a tech enthusiast currently working as frontend lead @secureship inc. He loves to build products that help people to solve their problems. Sometimes finding the right css units can be a pain. This tool will help you to figure out the right css units for your project.
	 */
	description: () => LocalizedString
	/**
	 * CSS units tool, HTML SEO optimization, web design CSS units, CSS unit converter, responsive design units, pixel to em converter, CSS length units, web development tools, CSS best practices, HTML coding tips, web design optimization, pixel conversion tool, EM and REM units, CSS measurement guide, design unit calculator, responsive web units, CSS layout tips, web development resources, HTML coding optimization, pixel-perfect design, wtf-css-unit
	 */
	keywords: () => LocalizedString
	/**
	 * @shamscorner
	 */
	appTwitterAccount: () => LocalizedString
	common: {
		/**
		 * etc
		 */
		etc: () => LocalizedString
		/**
		 * and many more...
		 */
		andManyMore: () => LocalizedString
		/**
		 * Figure out your CSS unit with ease. All you need to do is just answer some questions.
		 */
		slogan: () => LocalizedString
		/**
		 * Show
		 */
		show: () => LocalizedString
		/**
		 * Hide
		 */
		hide: () => LocalizedString
	}
	appLogo: {
		/**
		 * wtf-css-unit is created by Shamim Hossain who is a full-stack developer and a tech enthusiast currently working as frontend lead @secureship inc. He loves to build products that help people to solve their problems. Sometimes finding the right css units can be a pain. This tool will help you to figure out the right css units for your project.
		 */
		hrefTitle: () => LocalizedString
		/**
		 * wtf-css-unit Logo
		 */
		alt: () => LocalizedString
	}
	schemaMarkup: {
		/**
		 * Corporation
		 */
		type: () => LocalizedString
		/**
		 * shamscorner
		 */
		name: () => LocalizedString
		/**
		 * wtf-css-unit is created by Shamim Hossain who is a full-stack developer and a tech enthusiast currently working as frontend lead @secureship inc. He loves to build products that help people to solve their problems. Sometimes finding the right css units can be a pain. This tool will help you to figure out the right css units for your project.
		 */
		markupDescription: () => LocalizedString
		founder: {
			'0': {
				/**
				 * Person
				 */
				type: () => LocalizedString
				/**
				 * Shamim Hossain
				 */
				name: () => LocalizedString
			}
		}
		/**
		 * 2021-07-04
		 */
		foundingDate: () => LocalizedString
		contactPoint: {
			'0': {
				/**
				 * ContactPoint
				 */
				type: () => LocalizedString
				/**
				 * hossains159@gmail.com
				 */
				email: () => LocalizedString
				telephone: () => LocalizedString
				/**
				 * customer service
				 */
				contactType: () => LocalizedString
			}
		}
	}
	errorPage: {
		/**
		 * 404
		 */
		title: () => LocalizedString
		/**
		 * Not found
		 */
		subtitle: () => LocalizedString
		/**
		 * 404
		 */
		pageTitle: () => LocalizedString
		/**
		 * Looking for help? Reach out to me at hossains159@gmail.com
		 */
		description: () => LocalizedString
		/**
		 * Support, Contact, Help, 404, Not found
		 */
		keywords: () => LocalizedString
	}
	onboarding: {
		/**
		 * Hi, I'm <span class="font-semibold">Shamim Hossain</span>
		 */
		greeting: () => LocalizedString
		/**
		 * Answer some questions and I will help you to figure out the right CSS unit for your project.
		 */
		title: () => LocalizedString
		/**
		 * Assuming you are only using these units for web development, not for print media.
		 */
		subtitle: () => LocalizedString
		callToAction: {
			/**
			 * Let's Start
			 */
			letsStart: () => LocalizedString
		}
	}
	questionaries: {
		/**
		 * What are you declaring?
		 */
		title: () => LocalizedString
	}
	errors: {
		/**
		 * Something went wrong
		 */
		somethingWentWrong: () => LocalizedString
	}
}

export type Formatters = {}
